
Vagrant.configure("2") do |config|
 
  config.vm.box = "hashicorp/bionic64"
  config.vm.provision "shell", path: "../nginx/provision.sh"
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"
end
